import type { GeoPoint } from "./fieldTrackingService";
export type { GeoPoint };
export interface Halt { type: "halt"; lat: number; lng: number; startTime: string; endTime: string; durationMins: number; address?: string; radiusMetres: number; }
export interface Drive { type: "drive"; startTime: string; endTime: string; durationMins: number; distanceKm: number; }
export type TimelineEvent = Halt | Drive;
export interface DayTimeline { events: TimelineEvent[]; totalHalts: number; totalDrives: number; totalDistanceKm: number; totalHaltMins: number; totalDriveMins: number; }
const HALT_RADIUS_M=50,HALT_MIN_MINS=10,HALT_MIN_PTS=3;
function hav(a:GeoPoint,b:GeoPoint):number{const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,s=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(s),Math.sqrt(1-s));}
export function detectHalts(trail:GeoPoint[]):DayTimeline{if(!trail||trail.length<2)return{events:[],totalHalts:0,totalDrives:0,totalDistanceKm:0,totalHaltMins:0,totalDriveMins:0};const events:TimelineEvent[]=[];let i=0;while(i<trail.length){let j=i+1;while(j<trail.length&&hav(trail[i],trail[j])<HALT_RADIUS_M)j++;const pts=trail.slice(i,j);const mins=(new Date(trail[Math.min(j-1,trail.length-1)].ts).getTime()-new Date(trail[i].ts).getTime())/60000;if(pts.length>=HALT_MIN_PTS&&mins>=HALT_MIN_MINS){const cLat=pts.reduce((s,p)=>s+p.lat,0)/pts.length,cLng=pts.reduce((s,p)=>s+p.lng,0)/pts.length;events.push({type:"halt",lat:cLat,lng:cLng,startTime:trail[i].ts,endTime:trail[Math.min(j-1,trail.length-1)].ts,durationMins:Math.round(mins),radiusMetres:HALT_RADIUS_M});i=j;}else{const ds=i;let k=i+1;while(k<trail.length&&hav(trail[k-1],trail[k])>=HALT_RADIUS_M/3)k++;const de=Math.min(k,trail.length-1);const dm=(new Date(trail[de].ts).getTime()-new Date(trail[ds].ts).getTime())/60000;let dist=0;for(let m=ds+1;m<=de;m++)dist+=hav(trail[m-1],trail[m])/1000;if(dm>0)events.push({type:"drive",startTime:trail[ds].ts,endTime:trail[de].ts,durationMins:Math.round(dm),distanceKm:Math.round(dist*100)/100});i=Math.max(k,i+1);}}return{events,totalHalts:events.filter(e=>e.type==="halt").length,totalDrives:events.filter(e=>e.type==="drive").length,totalDistanceKm:events.filter(e=>e.type==="drive").reduce((s,e)=>s+(e as Drive).distanceKm,0),totalHaltMins:events.filter(e=>e.type==="halt").reduce((s,e)=>s+(e as Halt).durationMins,0),totalDriveMins:events.filter(e=>e.type==="drive").reduce((s,e)=>s+(e as Drive).durationMins,0)};}
let _t=0;
export async function reverseGeocode(lat:number,lng:number):Promise<string>{const w=Math.max(0,1100-(Date.now()-_t));if(w>0)await new Promise(r=>setTimeout(r,w));_t=Date.now();try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json`,{headers:{"User-Agent":"CleanCar360/1.0"}});const d=await r.json();const a=d.address||{};const pts=[a.neighbourhood,a.suburb,a.city_district,a.city].filter(Boolean);return pts.slice(0,3).join(", ")||`${lat.toFixed(4)}, ${lng.toFixed(4)}`;}catch{return`${lat.toFixed(4)}, ${lng.toFixed(4)}`;}}
export async function enrichHalts(tl:DayTimeline):Promise<DayTimeline>{for(const ev of tl.events){if(ev.type==="halt"&&!(ev as Halt).address)(ev as Halt).address=await reverseGeocode((ev as Halt).lat,(ev as Halt).lng);}return{...tl};}
